apiVersion: v1
appVersion: 1.63.0
version: 1.0.5
description: A Helm chart for Nexus IQ
name: nexusiq
keywords:
- sonatype
- nexusiq
- nexus
home: https://www.sonatype.com/nexus-iq-server
icon: http://www.sonatype.org/nexus/content/uploads/2015/06/Nexus-Logo.jpg
sources:
- https://help.sonatype.com/iqserver
- https://hub.docker.com/r/sonatype/nexus-iq-server
deprecated: true
